name: 업비트 api 활용 가상화폐 시세 조회
# program arguments :--job.name=tickerSlackJob market=KRW-BTC version=3
on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean :build -x test
      - name: Run batch
        run: java -jar -Dspring.batch.job.name=tickerSlackJob ./build/libs/crypto-automation-batch-1.0-SNAPSHOT-boot.jar market=KRW-BTC